apiVersion: v1
kind: Service
metadata:
  name: yb-masters
  namespace: yugabyte
  labels:
    app: yugabyte
    component: yb-master
spec:
  clusterIP: None
  ports:
  - name: ui
    port: 7000
  - name: rpc-port
    port: 7100
  selector:
    app: yugabyte
    component: yb-master