apiVersion: v1
kind: Service
metadata:
  name: yb-tservers
  namespace: yugabyte
  labels:
    app: yugabyte
    component: yb-tserver
spec:
  clusterIP: None
  ports:
  - name: ui
    port: 9000
  - name: rpc-port
    port: 9100
  - name: cassandra
    port: 9042
  - name: redis
    port: 6379
  - name: postgres
    port: 5433
  selector:
    app: yugabyte
    component: yb-tserver