apiVersion: v1
kind: Service
metadata:
  name: yb-master-external
  namespace: yugabyte
  labels:
    app: yb-master
    service-type: external
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 7000
    targetPort: 7000
    protocol: TCP
  - name: rpc-port
    port: 7100
    targetPort: 7100
    protocol: TCP
  selector:
    app: yb-master
---
apiVersion: v1
kind: Service
metadata:
  name: yb-tserver-external
  namespace: yugabyte
  labels:
    app: yb-tserver
    service-type: external
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: rpc-port
    port: 9100
    targetPort: 9100
    protocol: TCP
  - name: ysql
    port: 5433
    targetPort: 5433
    protocol: TCP
  - name: ycql
    port: 9042
    targetPort: 9042
    protocol: TCP
  selector:
    app: yb-tserver