version: '3.8'

services:
  oracle21c-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle21c-db
    ports:
      - "1521:1521"  # Changed back to standard port since it's separate
      - "5500:5500"  # Changed back to standard port since it's separate
    environment:
      ORACLE_PWD: "keycloak"
      ORACLE_SID: "ORCLCDB"
      ORACLE_PDB: "ORCLPDB1"
      ORACLE_CHARACTERSET: "AL32UTF8"
    volumes:
      - ./.docker/oracle-data21:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s sys/keycloak@//localhost:1521/ORCLPDB1 as sysdba"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 120s
    restart: unless-stopped